# Google Analytics Tracking ID
google_analytics:

# Default portfolio post
default_cover_image: /images/unsplash.png
default_post_title: Portfolio Item

menu:
  About: /about
  Product: /products
  Contact: /contact
